ENV["SINATRA_ENV"] ||= "development"

require_relative './config/environment'
require 'sinatra/activerecord/rake'

set :database, {adapter: "sqlite3", database: "db/development.sqlite3"}

task :console do
  Pry.start
end